version: '3'
services:
  zap:
    image: ghcr.io/zaproxy/zaproxy
    container_name: zap
    ports:
      - "8080:8080"
    volumes:
      - "C:/zap_scanner/reports:/zap/reports"
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8080
      -config api.key=*
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
